### PR TITLE
Introduce `RenderHelper` to reuse `StreamHelpers` in model broadcasts

### LINKED ISSUE #42: Detail on dispatch event seems to not get sent
My code in the model: `broadcast_dispatch_event_to user, target: 'calendar-container', name: 'move-event', detail: { task_id: id, start: calendar_start, end: calendar_end }`
CleanShot 2024-06-06 at 12 21 03@2x

### PR DESCRIPTION
**Pull request by marcoroth**
Fixes #42

### CODE REVIEW

**Comment by marcoroth** [comment]
/cc @dqnamo if you get a chance, would you mind testing if this branch fixes your issue:

```diff
# Gemfile

- gem "turbo_power"
+ gem "turbo_power", github: "marcoroth/turbo_power-rails", branch: "render-helper"
```

Thank you!

**Comment by dqnamo** [comment]
Yep, all works 🙌🏽

**Comment by marcoroth** [comment]
Awesome, thank you! I'm going to cut a release soon!

**Comment by marcoroth** [comment]
Just published https://github.com/marcoroth/turbo_power-rails/releases/tag/v0.6.2, let me know if you see something unexpected! Thank you!

**Pull request merged**
